baseURL = "https://encyclo-fute.pages.dev/"

languageCode = "fr"
title = "Encyclo Futé"
[pagination]
pagerSize = 10


buildFuture = false

# Important pour GitHub Pages en sous-dossier
relativeURLs = true
canonifyURLs = true

[taxonomies]
  category = "categories"

[params]
description = "Encyclopédie futée du quotidien : maison, auto, tech, administratif, minimalisme, organisation."

[menu]

  [[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Encyclopédie"
    url = "/encyclopedie/"
    weight = 2

  [[menu.main]]
    name = "Guides pratiques"
    url = "/guides/"
    weight = 3

  [[menu.main]]
    name = "Articles"
    url = "/articles/"
    weight = 4

  [[menu.main]]
    name = "Catégories"
    url = "/categories/"
    weight = 5

  [[menu.main]]
    name = "À propos"
    url = "/about/"
    weight = 6

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 7

