name: Build and Deploy Hugo site

on:
  schedule:
    - cron: "1 0 * * *"   # Tous les jours à 00h01
  workflow_dispatch:      # Permet de lancer manuellement si besoin

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
